apiVersion: v1
kind: Service
metadata:
  name: express-cluster-service
spec:
  selector:
    app: express-cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30877
  type: NodePort
